version: '3.7'
services:
  postgresqldb:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=calculator

  api-calculator:
    build:
      context: .
      dockerfile: .docker/Dockerfile.local
    environment:
      - DATABASE_HOST=postgresqldb
    depends_on:
      - postgresqldb
    expose:
      - 8080
    ports:
      - 8080:8080





